---
name: Convert Markdown to docx

on: workflow_dispatch

jobs:
    convert_via_pandoc:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Run Pandoc to convert Markdown to docx
              uses: docker://pandoc/extra
              with:
                args: output_report.md -o report.docx -f markdown -t docx
            
            - name: Upload PDF report
              uses: actions/upload-artifact@v4
              with:
                name: report.docx
                path: report.docx

            - name: Set Timestamp
              id: timestamp
              run: echo "TIMESTAMP=$(date +"%Y%m%d%H%M%S")" >> $GITHUB_ENV

            - name: Create Release
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                gh release create "tag-$TIMESTAMP" report.docx \
                --title "Output Report: $TIMESTAMP" \
                --notes "Word Document version of output_report.pdf (docx)" \
                --repo ${{ github.repository }}